project 'ChatChat.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatChat' do
use_frameworks!
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod  'Masonry'
pod 'Firebase/AdMob'
pod 'Firebase/Analytics'
pod 'Firebase/MLNLTranslate'
pod 'Firebase/MLCommon'
pod 'Firebase/MLNLSmartReply'
pod 'Firebase/MLNaturalLanguage'
pod 'Firebase/MLNLLanguageID'

pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Chips'
pod 'MaterialComponents/List'
pod 'MaterialComponents/TextFields'
pod 'MaterialComponents/Buttons+ButtonThemer'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatChat

end