project 'XML数据解析.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '10.14'

target 'XML数据解析' do
 pod 'GDataXMLNode2', '~> 2.0.1'  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XML数据解析

end
