project 'sqlite数据使用.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sqlite数据使用' do
 pod 'FMDB', '~> 2.7.5'
   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sqlite数据使用

end
