project '高机动画.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '高机动画' do
 pod 'HMGLTransitions', '~> 0.0.1'  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 高机动画

end
