project '富文本.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '富文本' do
pod 'Masonry'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 富文本

end
